version: '3'
services:
  utenti:
    build: ./user
    ports:
      - '4000:4000'
    depends_on:
      - dbutenti
      
    networks:
      - mynetwork
    restart: always

################################################
  libri:
    build: ./book
    ports:
      - '5000:5000'
    depends_on:
      - dbLIBRI
    networks:
      - mynetwork
    restart: always
   
  prestiti:  # Aggiungi il servizio 'prestiti'
    build: ./prestiti  # Sostituisci con la directory corretta
    ports:
      - '6000:6000'  # Porta di esposizione del servizio prestiti
    depends_on:
      - dbprestiti
    networks:
      - mynetwork
    command: ["python", "app.py"]
    restart: always


  

#############################   
  dbLIBRI:
    image: postgres:latest
    volumes:
      -  pgdataLIBRI:/var/lib/postgresql/data
    ports:
      - '13002:13002'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB: db_postgresLIBRI
    networks:
      - mynetwork
    restart: always

  dbutenti:
    image: postgres:latest
    volumes:
      -  pgdata:/var/lib/postgresql/data
    ports:
      - '13001:13001'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB: db_postgres
    networks:
      - mynetwork
    restart: always


  dbprestiti:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mysql
    ports:
      - '3310:3310'
    networks:
      - mynetwork
    restart: always

  

networks:
  mynetwork:
volumes:
  pgdata: {} 
  pgdataLIBRI : {}

