version: '3'
services:
  utenti:
    build: ./user
    ports:
      - '4000:4000'
    depends_on:
      - dbutenti
      
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB: db_postgres
    networks:
      - mynetwork
    restart: always
    links:
      - prestiti:prestitidb
################################################
  libri:
    build: ./book
    ports:
      - '5000:5000'
    depends_on:
      - dbLIBRI
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB: dbLIBRI
    networks:
      - mynetwork
    restart: always
    links:
      - prestiti:prestitidb
#####################################################################à
  prestiti:  # Aggiungi il servizio 'prestiti'
    build: ./prestiti  # Sostituisci con la directory corretta
    ports:
      - '6000:6000'  # Porta di esposizione del servizio prestiti
    depends_on:
      - dbprestiti
      - dbLIBRI
      - dbutenti
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mysql
    networks:
      - mynetwork
    restart: always

#############################ÀÀ    
  dbLIBRI:
    image: postgres:latest
    volumes:
      - pgdataLIBRI:/Scrivania/container
    ports:
      - '13002:13002'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB: db_postgresLIBRI
    networks:
      - mynetwork
    restart: always

  dbutenti:
    image: postgres:latest
    volumes:
      - pgdata:/Scrivania/container
    ports:
      - '13001:13001'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB: db_postgres
    networks:
      - mynetwork
    restart: always


  dbprestiti:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mysql
    ports:
      - '13000:13000'
    networks:
      - mynetwork
    restart: always









networks:
  mynetwork:
volumes:
  pgdata: {} 
  pgdataLIBRI : {}
 